### ISSUE TITLE
Assembler "Auto" tag nonfunctional

### ISSUE THREAD

**Issue by ResonanceChaos** [Gorea235/TaledensInvManagerUpdated#1]
Exception thrown when adding the AUTO tag to an assembler
left the tag on the assembler and recompiled and reran the script fresh, same exception.

From a fresh boot:
Last Run: 5
Caught exception during execution of script:
Object Reference not set to an instance of an object

**Comment by Gorea235** [comment]
Could you tell me what setup you have? I can't seem to replicate the issue, and that last step and the next are to do with quota panels, not assemblers.

**Comment by Mishka6783** [comment]
I found that the auto tag cycles too fast. on slower machines this could cause the exception. My issue is that it won't build anything as the code that detects the ore available in the assembler says no before it can be pulled.

**Comment by Shikifuyin** [comment]
Hi, recently got back to SE and have this issue ... it appears to mostly happen to SteelPlates for me,
they just jam after 1 job is resolved ... which make me think about an issue with your speed estimation
rather than a confilct with items being moved out before job is done (your code at first glance seems to
handle this safely).

After a quick look at the code (I may be wrong), in your ManageAssembler function, I noticed your speed
estimation takes the MAX with the previously computed speed which doesnt seem conservative if you
over estimate speed at some point (most likely due to execution time fluctuations caused by the game),
maybe using the MIN with the previous speed can fix this issue ?

This is just a first guess though ;)

**Comment by Gorea235** [comment]
I'll have a look when I can (I'm very busy at the moment), but I have wanted to adjust the assembly/refine speeds and quantities that TIM uses (since they are currently on the old values that were from the original script)

**Comment by Gorea235** [comment]
As of v1.7.3 I have adjusted the default update times, and I have increased the default item quantities that are given to the assemblers, so could someone check if this is still an issue (I haven't seen the issue in my worlds at all yet).

**Comment by Mishka6783** [comment]
Looks like it is resolved on my end. tested on dedicated server and single player.

**Comment by Gorea235** [comment]
Alright. Unless someone finds that this problem is still occuring, I'll close this issue
